
title: base43
description: bug bounty knowledge base
show_downloads: false
show_repo: false
theme: jekyll-theme-hacker
url: https://kevin-garnette.github.io/
author:
  name: Patrice Kenmoe
  email: noyau.imperatif@gmail.com 
  
year: 2021
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
